### ISSUE TITLE
missing ubuntu package: libtool

### ISSUE THREAD

**Issue by cliffordwolf** [riscv/riscv-tools#10]
I've just installed riscv-tools on ubuntu 15.04. In addition to the packages mentioned in README.md, I've also had to `apt-get install libtool`. Maybe you want to add it to the list in README.md.

**Comment by aswaterman** [comment]
Thanks, I'll fix this on the upstream branch.  I guess one of the other
packages happened to depend on libtool in 14.04 but not 15.04.
