### ISSUE TITLE
make ARCH=riscv error

### ISSUE THREAD

**Issue by kllbrd** [riscv/riscv-tools#103]
Hello,
When I try to `make ARCH=riscv` I'm taking these errors:

[root@localhost linux-3.14.33]# make j=2 ARCH=riscv
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CC      kernel/bounds.s
gcc: error: unrecognized argument in option ‘-mabi=lp64’
gcc: note: valid arguments to ‘-mabi=’ are: ms sysv
gcc: error: unrecognized command line option ‘-mno-save-restore’; did you mean ‘-Wno-selector’?
Kbuild:20: recipe for target 'kernel/bounds.s' failed
make[1]: *** [kernel/bounds.s] Error 1
Makefile:1069: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2

-----update-----

I exported to CROSS_COMPILE the riscv64-unknown-linux-gnu- and I tried to make again. Now I am taking these:
[root@localhost linux-3.14.33]# make j=2 ARCH=riscv
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CC      kernel/bounds.s
riscv64-unknown-linux-gnu-gcc: error: unrecognized command line option '-mabi=lp64'
Kbuild:20: recipe for target 'kernel/bounds.s' failed
make[1]: *** [kernel/bounds.s] Error 1
Makefile:1069: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2

Any kind of help would be appreciated.
Thanks!

**Comment by kito-cheng** [comment]
https://github.com/riscv/riscv-tools/issues/79

**Comment by kllbrd** [comment]
Thank you!
