### ISSUE TITLE
libtoolize error

### ISSUE THREAD

**Issue by esolera** [riscv/riscv-tools#108]
when i tried to run the build i have this problem

libtoolize:   error: 'build-aux/install-sh' is newer: use '--force' to overwrite
Building project riscv-openocd
ar: `u' modifier ignored since `D' is the default (see `U')

**Comment by jim-wilson** [comment]
The libtoolize error is an ignorable error, and won't cause the build to fail.  The ar warning is just a warning, and won't cause the build to fail.  I don't see any actual problem here.  Given the age of the issue, and the lack of any actual problem, I don't think this is useful anymore.
