### ISSUE TITLE
Executable segfaulting when running with spike and pk

### ISSUE THREAD

**Issue by zhemao** [riscv/riscv-tools#11]
I wrote a test program in C consisting of an empty main method. When running it with spike and pk, the PC jumps to address fffffffffffffffe and segfaults. After running spike with a commitlog, I've discovered that the problem lies somewhere in the procedure linkage table in the test executable. 

Error Message:

    z  0000000000000000 ra 0000000000000000 sp 00000000fefffb50 gp 0000000000802f30
    tp 0000000000000000 t0 0000000000000000 t1 0000000000000000 t2 00000000008022b0
    s0 0000000000000000 s1 0000000000000000 a0 00000000008003e8 a1 0000000000000001
    a2 00000000fefffb58 a3 00000000008003f0 a4 0000000000800480 a5 0000000000000000
    a6 00000000fefffb50 a7 0000000000000000 s2 0000000000000000 s3 0000000000000000
    s4 0000000000000000 s5 0000000000000000 s6 0000000000000000 s7 0000000000000000
    s8 0000000000000000 s9 0000000000000000 sA 0000000000000000 sB 0000000000000000
    t3 ffffffffffffffff t4 0000000000000000 t5 0000000000000000 t6 0000000000000000
    pc fffffffffffffffe va 0000000000000000 insn       ffffffff sr 8000000000003008
    User fetch segfault @ 0xfffffffffffffffe
Commit Log:

    0x0000000000002950 (0x10000073)
    0x0000000000002950 (0x10000073)
    0x00000000008002e0 (0x00003197) x 3 0x00000000008032e0
    0x00000000008002e4 (0xc5018193) x 3 0x0000000000802f30
    0x00000000008002e8 (0x00050793) x15 0x0000000000000000
    0x00000000008002ec (0x00000517) x10 0x00000000008002ec
    0x00000000008002f0 (0x0fc50513) x10 0x00000000008003e8
    0x00000000008002f4 (0x00013583) x11 0x0000000000000001
    0x00000000008002f8 (0x00810613) x12 0x00000000fefffb58
    0x00000000008002fc (0xff017113) x 2 0x00000000fefffb50
    0x0000000000800300 (0x00000697) x13 0x0000000000800300
    0x0000000000800304 (0x0f068693) x13 0x00000000008003f0
    0x0000000000800308 (0x00000717) x14 0x0000000000800308
    0x000000000080030c (0x17870713) x14 0x0000000000800480
    0x0000000000800310 (0x00010813) x16 0x00000000fefffb50
    0x0000000000800314 (0xfbdff06f)
    0x00000000008002d0 (0x00002317) x 6 0x00000000008022d0
    0x00000000008002d4 (0x45033283) x 5 0x00000000008002b0
    0x00000000008002d8 (0x00028367) x 6 0x00000000008002dc
    0x00000000008002b0 (0x00002397) x 7 0x00000000008022b0
    0x00000000008002b4 (0x40530333) x 6 0x000000000000002c
    0x00000000008002b8 (0x4603be03) x28 0xffffffffffffffff
    0x00000000008002bc (0xfd430313) x 6 0x0000000000000000
    0x00000000008002c0 (0x46038293) x 5 0x0000000000802710
    0x00000000008002c4 (0x00135313) x 6 0x0000000000000000
    0x00000000008002c8 (0x0082b283) x 5 0x0000000000000000
    0x00000000008002cc (0x000e0067)

Program disassembly:

    test:     file format elf64-littleriscv
    
    
    Disassembly of section .plt:
    
    00000000008002b0 <_PROCEDURE_LINKAGE_TABLE_>:
      8002b0:       97 23 00 00 33 03 53 40 03 be 03 46 13 03 43 fd     .#..3.S@...F..C.
      8002c0:       93 82 03 46 13 53 13 00 83 b2 82 00 67 00 0e 00     ...F.S......g...
    
    00000000008002d0 <__libc_start_main@plt>:
      8002d0:       00002317                auipc   t1,0x2
      8002d4:       45033283                ld      t0,1104(t1) # 802720 <__TMC_END__+0x10>
      8002d8:       00028367                jalr    t1,t0
      8002dc:       00000013                nop
    
    Disassembly of section .text:
    
    00000000008002e0 <_start>:
      8002e0:       00003197                auipc   gp,0x3
      8002e4:       c5018193                addi    gp,gp,-944 # 802f30 <_gp>
      8002e8:       00050793                mv      a5,a0
      8002ec:       00000517                auipc   a0,0x0
      8002f0:       0fc50513                addi    a0,a0,252 # 8003e8 <main>
      8002f4:       00013583                ld      a1,0(sp)
      8002f8:       00810613                addi    a2,sp,8
      8002fc:       ff017113                andi    sp,sp,-16
      800300:       00000697                auipc   a3,0x0
      800304:       0f068693                addi    a3,a3,240 # 8003f0 <__libc_csu_init>
      800308:       00000717                auipc   a4,0x0
      80030c:       17870713                addi    a4,a4,376 # 800480 <__libc_csu_fini>
      800310:       00010813                mv      a6,sp
      800314:       fbdff06f                j       8002d0 <__libc_start_main@plt>

**Comment by aswaterman** [comment]
The problem is probably that it is a dynamically-linked program.  Try compiling it again with -static.

I will see if I can catch this before program execution to print a sensible error message.
