### ISSUE TITLE
The compilation guide probably shouldn't recommend make -j without a number

### ISSUE THREAD

**Issue by neuschaefer** [riscv/riscv-tools#12]
Hi,

The guide in README.md currently uses `make -j` (without a number) in three places. If `make` is actually called that way, it will spawn as many concurrent processes as the makefile allows, effectively acting as a fork bomb on larger projects. To avoid this, I'd recommend using a default number of jobs in the examples, e.g. `make -j 16`.

**Comment by palmer-dabbelt** [comment]
Dos #13 look OK?

**Comment by neuschaefer** [comment]
Yes. Thanks!
