### ISSUE TITLE
when should this repo be updated?

### ISSUE THREAD

**Issue by timsifive** [riscv/riscv-tools#160]
It's not clear to me when this repo can/needs to be updated. Personally I would love to see it auto-update when any of the repos it contains have an update.

What's the intent?

**Comment by mwachs5** [comment]
The intent of this repo is to provide a single commit of all the different submodules that are known to work together. For example, GCC should to be compatible with RISC-V ISA sim as features are added, with the riscv-tests, etc. Without this repo tying them together, Users have to figure out what version of everything they are supposed to use together.

So, I'd say this repo needs to be updated if one or more submodules are updated in a meaningful way, and need to be communicated to RISC-V users. It's harder for users if they need to track the versions of all subrepos seperately to understand which work with which, updating this repo stamps a version of the tools/tests/simulators which all work together.
