### ISSUE TITLE
Need bc tool to compile Linux

### ISSUE THREAD

**Issue by sbates130272** [riscv/riscv-tools#17]
Hi

Great notes here but I noticed that to compile the Linux kernel for RISCV you need the Linux bc tool and that is not installed by default on Ubuntu. So you might want to add it to your list of apt-get install in your READMEs on this repo and some of the submodule repos.

Thanks - Stephen

**Comment by aswaterman** [comment]
Thanks for pointing that out, Stephen; I've updated them.

**Comment by sbates130272** [comment]
Cool, good to close this issue!
