### ISSUE TITLE
Build Script Fails (mkdir)

### ISSUE THREAD

**Issue by lfernand4** [riscv/riscv-tools#177]
![image](https://user-images.githubusercontent.com/36438648/36600256-18326b22-18b2-11e8-856b-6fb1acfbf42e.png)
Can somone help me ?

**Comment by jim-wilson** [comment]
You don't have the entire source tree.  Note that the riscv-oipenocd dir is empty.  You must do
  git submodule update --init --recursive
to get the rest of the source tree.

I don't recommend use of riscv-tools; it is poorly maintained.  I would suggest riscv/riscv-gnu-toolchain if you want a compiler, and sifive/freedom-u-sdk if you want compiler+linux kernel+buildroot.  riscv-tools might be useful if you want to learn how to build a linux system from scratch, as the README.md file takes you through a lot of the necessary steps, one by one.
