### ISSUE TITLE
SPIKE does not generate illegal instruction exception for c.sxxi instructions encoded with zero shift amount

### ISSUE THREAD

**Issue by deepsrc** [riscv/riscv-tools#183]
One of our directed tests is failing on SPIKE. It is not detecting the half-word 0x8601 (i.e. c.srai encoded with zero shift amount) as an illegal instruction. According to the RISC-V spec, shift amount of 0 is illegal for c.slli, c.srai and c.srli instructions in RV32C.

The same test when executed on PULPino runs alright.

**Comment by aswaterman** [comment]
Feel free to make a pull request against riscv-isa-sim to address this problem.

**Comment by deepsrc** [comment]
Just submitted a pull request. I have tested the changes. They are working fine now.

**Comment by aswaterman** [comment]
Thanks
