### ISSUE TITLE
The benchmark of dhrystone score was lower than the Official data

### ISSUE THREAD

**Issue by IC-Dream** [riscv/riscv-tools#211]
Hi, 

I'm doing some research using RISC-V RocketChip, and when i run benchmark of dhrystone (Verilator) by DefualtConfig, got the follwing result:

Dhrystones per Second:                          2005

So,DMIPS/MHz = 2005/1757 = 1.14

it seems that the score is lower than the official data(1.72DIMPS/MHz) https://www.hotchips.org/wp-content/uploads/hc_archives/hc27/HC27.25-Tuesday-Epub/HC27.25.70-Processors-Epub/HC27.25.731-RISC-V-Lee-UCB-V4.with-backup.pdf

There must be someting wrong, how could i reach the 1.72DIMPS/MHz ?

Thanks

**Comment by aswaterman** [comment]
The Dhrystone program built from riscv-tests doesn't use an optimized C library, and it might not use the best set of compiler flags.  The data reported in the presentation you referenced used an optimized C library.  For Dhrystone, the `strcmp` routine has a first-order impact on performance.

Unfortunately, we don't have the resources to help with benchmarking here.

**Comment by IC-Dream** [comment]
@aswaterman i mentioned that there are two build modes: a generic ELF/Newlib toolchain and a more sophisticated Linux-ELF/glibc toolchain. So the default build modes was the former, right? could we swith to the latter to run simulation(Verilator).
