### ISSUE TITLE
Someting wrong with your pictures

### ISSUE THREAD

**Issue by hyf6661669** [riscv/riscv-tools#217]
Hi, I have found that the pictures in the README.md of the riscv-tools can't be loaded correctly. If I click the picture, it returns "Non-Image content-type returned". So I guess maybe there is someting wrong with your online pictures, or it is due to my web browser's problems?

Can you fix this problem? THANKS!!!

**Comment by jim-wilson** [comment]
There are no pictures in the README.md file.  It is simply a mark down text file.  Why do you think that there are pictures in it?  What exactly isn't displaying correctly?

**Comment by hyf6661669** [comment]
For example, in my web browser, I can only see this:
![pic1](https://user-images.githubusercontent.com/18757974/41203406-d6032196-6d08-11e8-8f97-1cea1303963f.png)
I think there should be a picture shwoing the Linux kernel menuconfig interface?

**Comment by jim-wilson** [comment]
I missed that.  It is just a URL in the README.md file.

Cross project references in a README.md file aren't wise.  We shouldn't expect install-guides to come back.  But I also think this picture isn't very important.  Maybe we can just drop it from the README.md file.

**Comment by palmer-dabbelt** [comment]
@rickoco Did the RISC-V website change paths?  Is there a new URL for http://riscv.org/install-guides/linux-boot.png ?

**Comment by palmer-dabbelt** [comment]
OK, I can't find the image at RISC-V.  @a0u @qmn do either of you have these photos floating around?  If not we can just drop it.

**Comment by a0u** [comment]
@palmer-dabbelt https://web.archive.org/web/20170604023943im_/https://www.ocf.berkeley.edu/~qmn/linux/linux-menuconfig.png
