### ISSUE TITLE
no matching function for call to dtm_t::dtm_t

### ISSUE THREAD

**Issue by abdullahyildiz** [riscv/riscv-tools#232]
I'm using commit f86271fe4f0b716f05dcadf1d4e47f796cb7a6d4.

When I type `make CONFIG=MegaBoomConfig` in verisim, I get the following error:

`/archive/HDD5/ayildiz/boom-template/rocket-chip/csrc/SimDTM.cc:47:64: error: no matching function for call to dtm_t::dtm_t(std::vector<std::basic_string<char> >)  dtm = new dtm_t(filter_argv_for_dtm(info.argc, info.argv));`

**Comment by jim-wilson** [comment]
This doesn't appear to be a riscv-tools problem.

I found a similar bug report here:
https://github.com/freechipsproject/rocket-chip/issues/1384
which suggests that this is a versioning problem, e.g. mismatched versions of rocket-chip, fesvr, and maybe other stuff.  Anyways, the rocket-chip repo looks like a much better place to discuss this problem.
