### ISSUE TITLE
make output/rv64ui-p-simple.out:Error

### ISSUE THREAD

**Issue by ferdous313** [riscv/riscv-tools#249]
Hi,
I am getting error when I am trying to run a test  in /boom-template/verisim
mada0:~/boom-template/verisim$pwd
/soe/nferdous/boom-template/verisim
mada0:~/boom-template/verisim$ make output/rv64ui-p-simple.out
Error message:
make[1]: Leaving directory '/mada/users/nferdous/boom-template/verisim/generated-src/boom.system.TestHarness.BoomConfig'
make: *** No rule to make target '/soe/nferdous/rocket-chip/riscv-tools/riscv64-unknown-elf/share/riscv-tests/isa/rv64ui-p-simple', needed by 'output/rv64ui-p-simple'.  Stop
Any suggestion will be appreciated.

**Comment by ferdous313** [comment]
Hi,
I am getting error when I am trying to run a test in /boom-template/verisim
/boom-template/verisim$pwd
boom-template/verisim
/boom-template/verisim$ make output/rv64ui-p-simple.out
Error message:
make[1]: Leaving directory '/mada/users/nferdous/boom-template/verisim/generated-src/boom.system.TestHarness.BoomConfig'
make: *** No rule to make target '/soe/nferdous/rocket-chip/riscv-tools/riscv64-unknown-elf/share/riscv-tests/isa/rv64ui-p-simple', needed by 'output/rv64ui-p-simple'. Stop
Any suggestion will be appreciated.

**Comment by palmer-dabbelt** [comment]
This doesn't look like a riscv-tools bug, but instead is probably some sort of mismatch between your test harneess and riscv-tools.  @ccelio would be the best bet here, as it appears you're using BOOM.  You should try to make sure all your versions match correctly, as that's usually the issue.

I'm going to close this, as it's not a riscv-tools bug.

**Comment by ferdous313** [comment]
ok Thanks!
