### ISSUE TITLE
how can we use make jobs (make -j)

### ISSUE THREAD

**Issue by gregf** [riscv/riscv-tools#250]
Is there a way I can pass make -j8 or similar into build-rv32ima.sh or do our own custom build instructions that use parallel make to speed up the process for our CI environment? Thanks.

**Comment by jim-wilson** [comment]
You can set the MAKEFLAGS environment variable to include the make options you want.  Or you can just edit the build.common file because there is only one place where make is called to do builds.

**Comment by gregf** [comment]
Thanks!
