### ISSUE TITLE
build.sh: GDB not automatically installed?

### ISSUE THREAD

**Issue by neuschaefer** [riscv/riscv-tools#28]
Hi,

I was trying to integrate the spike test suite into the riscv-tools `.travis.yml`, but I noticed that gdb wasn't installed ([build log](https://travis-ci.org/neuschaefer/riscv-tools/builds/135219360)). I also noticed that the riscv-gnu-toolchain Makefile.in uses `--disable-gdb` in a few places. What's the status of testing gdb in travis?

**Comment by palmer-dabbelt** [comment]
Up until a few days ago, GDB didn't build with the standard RISC-V binutils releases (it was ported on another branch).  That's why the builds are disabled.  I'd accept a patch turning it on, now that it should actually work.

**Comment by neuschaefer** [comment]
I'll see if I can write a patch.

**Comment by timsifive** [comment]
Just want to add that I'd love for this to be fixed. gdb wasn't building for me, and I suspect it's because people just run "build.sh" and if that passes, they think their changes are good.

**Comment by palmer-dabbelt** [comment]
This should be fixed.
