### ISSUE TITLE
riscv-tools title is wrong

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-tools#286]
Says it includes a GNU toolchain.  It no longer does.  This is on the code tab right below the word code in the tab.

**Comment by gurjeet** [comment]
<img width="437" alt="Screen Shot 2019-04-03 at 11 38 43 AM" src="https://user-images.githubusercontent.com/159099/55504215-3ecda300-5605-11e9-8309-68d8a3d4d024.png">

**Comment by aswaterman** [comment]
Fixed
