### ISSUE TITLE
How to make riscv-gcc compile new csr register？

### ISSUE THREAD

**Issue by 245950258** [riscv/riscv-tools#289]
I am working on rocket-chip. Recently, I added a new CSR register to my rocket-chip. However, it looks like that the RISCV-GCC can't compile my program.
    So, I want to know if the RISCV-TOOLS supports to add a new CSR register.

**Comment by jim-wilson** [comment]
The toolchain is riscv-gnu-toolchain, not riscv-tools.

You can always use the CSR register number.  If you want to use the CSR name, then you need to modify binutils to add assembler/disassembler support for the new name.  In binutils, see the file include/opcode/riscv-opc.h and look for example at the CSR_MSTATUS support.  You need two lines, one which gives the register number, and one which maps the register number to the name string.

**Comment by 245950258** [comment]
Thank you for helping me.
