### ISSUE TITLE
 configure: error: Spike requires a little-endian host

### ISSUE THREAD

**Issue by yanjy1215** [riscv/riscv-tools#306]
My host is a little-endian host. however, this error shows

**Comment by jim-wilson** [comment]
Check the file riscv-isa-sim/build/config.log.  You will see a message something like
configure:3825: checking whether byte ordering is bigendian
and then a lot of tests compiling small files checking to see if we get a big-endian result.  One of these tests must have failed.  This should show in the log, though you may have to cross reference with the riscv-isa-sim/configure file to see what is going on.

It isn't a question of whether the build system is little-endian, but whether the C and C++ compilers are emitting little-endian code by default.  If you have a bi-endian system, or a non-host cross compiler as $CC, then these tests could fail.

**Comment by yanjy1215** [comment]
thanks! It is caused by g++ version
