### ISSUE TITLE
Which instruction set combination can support a simple Linux operating system

### ISSUE THREAD

**Issue by LangQingjie** [riscv/riscv-tools#348]
Hello, I am preparing to develop a processor core that can support Linux operating system in order to complete my course homework. But now I'm very confused because I don't know which instruction set is the least needed to support a Linux operating system.

**Comment by aswaterman** [comment]
Please refrain from cross-posting.  I'll answer on your other post at https://github.com/riscv/riscv-isa-sim/issues/787
