### ISSUE TITLE
bbl loader ../pk/elf.c:41: assertion failed: IS_ELF64(eh) Power off

### ISSUE THREAD

**Issue by Manahil14** [riscv/riscv-tools#359]
spike pk /home/akeana/proj/cores/aqlrv32-main/sw/hello/hello.elf
I am trying to use elf generated by my core in spike pk. but it gives this error message.

bbl loader 
../pk/elf.c:41: assertion failed: IS_ELF64(eh) 
Power off

I want to run my 32-architecture elf in spike for testing.

**Comment by aswaterman** [comment]
riscv-tools isn't supported.

But it sounds like you're trying to run a 32-bit binary on a 64-bit host.

**Comment by Manahil14** [comment]
But spike can also work on 32-bit
