### ISSUE TITLE
Can the priv-1.9.1 work go on a separate branch than priv-1.9?

### ISSUE THREAD

**Issue by acw1251** [riscv/riscv-tools#40]
Right now the priv-1.9 branch includes some changes from future privileged specs (priv 1.9.1 according to commits), and some of those changes aren't compatible with priv-1.9 (for example: misa's CSR number changed). Is it possible to keep the priv-1.9 branch as just priv-1.9 and move the priv-1.9.1 work to a separate branch? Tags or releases would work as well for priv-1.9.

**Comment by aswaterman** [comment]
I meant to tag a release.  I'll do that.

**Comment by aswaterman** [comment]
https://github.com/riscv/riscv-tools/releases/tag/priv-1.9-rc0

**Comment by palmer-dabbelt** [comment]
I think we resolved this sufficiently.
