### ISSUE TITLE
32bit simulation error on isa RV32I

### ISSUE THREAD

**Issue by songchengwei** [riscv/riscv-tools#42]
Hi,  I download the riscv-tools, install the tool with --with-xlen=32 option, I can successfully run hello world with [https://github.com/riscv/riscv-tools/issues/41](issue 41), then I try to compile C code with the specific RV32I ISA, I tried two ways:

1, I try to use compile option -march=RV32I to compile the C code, and then use command:  spike --isa=RV32I /path/to/32bit/pk/pk hello. There is no output, but if I change the command to spike --isa=RV32, the output is as expected.
2, I try to install the tool-chain with option --with-arch=I --with-xlen=32, the result is as 1.

Is there anything wrong? How can I only use RV32I isa?

**Comment by mehnadnerd** [comment]
I ran into some similar issues. I have found that the M and A extensions appear to be required in order to use C functions like printf (or puts, which it optimises it to). I am not sure how to resolve this issue.

**Comment by palmer-dabbelt** [comment]
You probably have a C library that was built for rv32ima.  If you build one for rv32i then you shouldn't have any M or A instructions.

**Comment by mehnadnerd** [comment]
I've found the instructions for how to do so here: https://github.com/ucb-bar/riscv-sodor#building-a-rv32i-toolchain.

**Comment by jim-wilson** [comment]
Already answered.
