### ISSUE TITLE
Breakpoint test failure

### ISSUE THREAD

**Issue by colinschmidt** [riscv/riscv-tools#45]
Building the commit checked into rocket-chip 83a3143e93b54d705f38588b3e14351434084bae with build.sh works fine until you run the isa tests.

```
$ cd riscv-tests/isa
$ make run
...
  [ FAILED ] rv64mi-p-breakpoint.out     (tohost = 5)
  [ FAILED ] rv32mi-p-breakpoint.out32   (tohost = 5)
```

This corresponds to the test commented "Make sure writes don't trap"

**Comment by aswaterman** [comment]
Seems unrelated but I'll look into it.

**Comment by aswaterman** [comment]
451b3dfbf659ae6135b56c0d7408b90fa22cdea5 should resolve this.
