### ISSUE TITLE
Script build failure on REHL4

### ISSUE THREAD

**Issue by purlvin** [riscv/riscv-tools#57]
I got below build error, just wondering is REHL4 supported? 
Completely no idea on this error, can anyone provide a tip? 
Thanks~

> 214%./build.sh
> Starting RISC-V Toolchain build process
> 
> Removing existing riscv-fesvr/build directory
> Configuring project riscv-fesvr
> Building project riscv-fesvr
> /tmp/ccb4mrHV.s: Assembler messages:
> /tmp/ccb4mrHV.s:693: Error: unknown pseudo-op: `.cfi_personality'
> /tmp/ccb4mrHV.s:694: Error: unknown pseudo-op: `.cfi_lsda'
> gmake: *** [elfloader.o] Error 1
>

**Comment by jim-wilson** [comment]
Looks like an incompatibility between your host C++ compiler and assembler.  You might have mismatched versions of them.  Or maybe you accidentally used the wrong C++ compiler.  You can find the build log with a little more info in riscv-fesvr/build/build.log.  There isn't enough info in this issue to reproduce the problem or determine what it is.
