### ISSUE TITLE
count retired instruction

### ISSUE THREAD

**Issue by NAOUSS** [riscv/riscv-tools#60]
Hello,

RDINSTRET allows us to know the number of instruction retired by processor and by thread i thing.
is it a way to know the number of retired instruction by each execution unit ?
for example : BOOM core 3 issues has 6 execution units, i would like to know the number of instruction retired by each execution units (ALU, FP ...) for each thread.

Thank you in advance

**Comment by palmer-dabbelt** [comment]
This isn't really a risc-tools issue, but one for the individual platforms.  If you're specifically looking for BOOM performance counters then I'd suggest opening a bug against the BOOM repo.  These will probably be exposed as either platform-specific memory-mapped registers (which require no toolchain support) or platform-specific CSRs (we already have the arbitrary CSR indexing scheme).
