### ISSUE TITLE
spike pk hello, error: terminate called after throwing an instance of 'trap_store_access_fault'

### ISSUE THREAD

**Issue by tinna0529** [riscv/riscv-tools#63]
./build.sh
riscv toolchain build success

riscv64-unknown-elf-gcc hello.c 
spike pk a.out
terminate called after throwing an instance of 'trap_store_access_fault'

**Comment by palmer-dabbelt** [comment]
Sorry, but there's not really enough information here for anyone to help you debug this.

I'm going to close this bug, but feel free to reopen it if you have more information.

**Comment by tinna0529** [comment]
I change the VM OS from ubuntu-16.04-desktop-i386 to ubuntu-14.04.5-desktop-amd64.
gcc g++ 4.8.4
apt-get install device-tree-compiler

so the spike is OK!
