### ISSUE TITLE
building riscv-isa-sim fails on MacBook

### ISSUE THREAD

**Issue by kuopinghsu** [riscv/riscv-tools#69]
I got error messages when I built the riscv-isa-sim on my MacBook.

…
../riscv/devices.h:45:19: error: use of undeclared identifier 'calloc'
    data = (char*)calloc(1, size);
…
../riscv/devices.h:50:14: error: use of undeclared identifier 'free'; did you
      mean 'freg'?
  ~mem_t() { free(data); }
…
../riscv/devices.h:47:60: error: no member named 'to_string' in namespace 'std'
      throw std::runtime_error("couldn't allocate " + std::to_string(siz...

Here is the patch file to fix this problem.

diff --git a/riscv/devices.h b/riscv/devices.h
index ba344db..59e1e7e 100644
--- a/riscv/devices.h
+++ b/riscv/devices.h
@@ -2,6 +2,8 @@
#define _RISCV_DEVICES_H

 #include "decode.h"
+#include &lt;cstdlib&gt;
+#include &lt;string&gt;
#include &lt;map&gt;
#include &lt;vector&gt;

**Comment by palmer-dabbelt** [comment]
This should be fixed by the riscv-isa-sim commit, so I'm closing this bug.  Feel free to reopen it if something went wrong.

Thanks for the patch!
