### ISSUE TITLE
CC=riscv64-unknown-elf-gcc  in pk build line in build.sh

### ISSUE THREAD

**Issue by sherry151** [riscv/riscv-tools#8]
I think the pk build line should export CC=riscv64-unknown-elf-gcc before invoking the build.

CC=riscv64-unknown-elf-gcc build_project riscv-pk --prefix=$RISCV/riscv64-unknown-elf --host=riscv64-unknown-elf

It got removed in commit 2991201a5263ee9e88ca380d53383cf67e3eae59 

This option is necessary as the user might want to build the other projects with a custom gcc.

**Comment by aswaterman** [comment]
Sorry for not noticing this earlier.  You are quite right.  We opted to update the documentation to not suggest users use CC= and CXX= to force the use of another compiler.  If you accomplish this by manipulating your PATH instead, there's no need to use CC= again on the pk build.
