### ISSUE TITLE
rootfs.cpio 

### ISSUE THREAD

**Issue by ninode** [riscv/riscv-tools#81]
Hello,

My linux directory has the following files:
```
linux-3.14.33$ ls
arch     Documentation  ipc          Makefile        README.md  System.map
block    drivers        Kbuild       mm              root       tools
certs    firmware       Kconfig      modules.order   samples    usr
COPYING  fs             kernel       Module.symvers  scripts    virt
CREDITS  include        lib          net             security   vmlinux
crypto   init           MAINTAINERS  README          sound      vmlinux.o
```
I cannot find rootfs.cpio with find . | cpio --quiet -o -H newc > linux-3.14.33/rootfs.cpio
Where is <riscv-linux> supposed to be ?
Can you please help ? 

Thank you

**Comment by palmer-dabbelt** [comment]
Running

````
find . | cpio --quiet -o -H newc > linux-3.14.33/rootfs.cpio
````

generates rootfs.cpio, that's what the > operator in BASH does <http://ryanstutorials.net/linuxtutorial/piping.php>.

Here's some info on creating initframfs CPIOs <http://jootamam.net/howto-initramfs-image.htm>, which I'm assuming is what you're trying to do?
